### ISSUE TITLE
 ~~ERROR~~ NullPointerException: null

### ISSUE THREAD

**Issue by SSenZ0** [Quarris/RebirthOfTheMobs#12]
Minecraft 1.12.2

rotm-1.12.2-1.1.2

twilightforest-1.12.2-3.11.1021-universal

Custom made modpack, contact  [✦SenZ#9047 via discord for more information.

Game Crashes upon loading into the Twilight Forest's Hydra spawn range.
Removing ROTM Completely fixes the issue.
Full Crashreport below via paste.gg

[**Crashreport**](https://paste.gg/p/anonymous/0c0fb5e2d8364cac996c52ac0ad18900)

**Comment by Quarris** [comment]
Could you send me the rotm.cfg file used in the pack?

**Comment by SSenZ0** [comment]
> Could you send me the rotm.cfg file used in the pack?


[rotm.cfg](https://paste.gg/p/anonymous/2b2895e2d22942d989501938ab383b89)

**Comment by Quarris** [comment]
https://drive.google.com/file/d/165f_izNnSkr8TgSirksQl_4GPBPDqh6_/view?usp=sharing Could you check if this version works?

**Comment by SSenZ0** [comment]
> https://drive.google.com/file/d/165f_izNnSkr8TgSirksQl_4GPBPDqh6_/view?usp=sharing Could you check if this version works?

Oh my god, yes! That fixed it! Thank you so much!
