### ISSUE TITLE
cooldownRange not applying correctly in S:"Summon Spawns" <

### ISSUE THREAD

**Issue by SSenZ0** [Quarris/RebirthOfTheMobs#13]
### #version#

ROTM 1.1.3

### #Behavior#

As soon as a mob reaches it's set HP value to spawn minions it will spawn it's minions over and over again as soon as it took damage which looks like this after about 2 seconds

![image](https://user-images.githubusercontent.com/83184329/119162511-bfa4be80-ba5a-11eb-9335-ae74d8bdab5c.png)

### #Expected Behavior#

Golem should spawn 4-6 Blazed on 89% Health every 8-12 Seconds.

### #config line#

**battletowers:golem;minecraft:blaze;89;4-6;8-12;false;false;10;false;true;true;{CustomName:"§cAncient Defender"}**

### #other mods#

custom modpack called sayva, modlist can be found below
[MODLIST](https://www.curseforge.com/minecraft/modpacks/sayva/relations/dependencies)

**Comment by Quarris** [comment]
Does this happen if you put a different master entity in?
Are you able to test this config with just the battletowers mod to see if the issue persist?

**Comment by SSenZ0** [comment]
> Does this happen if you put a different master entity in?
> Are you able to test this config with just the battletowers mod to see if the issue persist?

also happens to our wither, so it's not battletower related.

**Comment by Quarris** [comment]
Could you tell me the mod which adds the variations for mobs?

**Comment by SSenZ0** [comment]
> Could you tell me the mod which adds the variations for mobs?

Special Mobs, and Primitive Mobs

**Comment by Quarris** [comment]
Good news: I have figured out the issue.
Bad News: I have no clue how to fix it.

As far as I can see, it's an issue with how Special Mobs is replacing the entities spawned, with their own entities. Basically they cancel the default spawning mechanics, which my mod captures it as a failed spawn. This therefore does not start the cooldown, which is why you see them spawn constantly. Then SpecialMobs respawns the mob, which I cannot detect directly, and therefore that mob doesnt get counted my my Spawn Summons capability.

I will try to figure this out but you may want to escalate this with the Special Mobs dev to see if they can do something on their side and link them this so they can see the explanation

**Comment by SSenZ0** [comment]
> Good news: I have figured out the issue.
> Bad News: I have no clue how to fix it.
> 
> As far as I can see, it's an issue with how Special Mobs is replacing the entities spawned, with their own entities. Basically they cancel the default spawning mechanics, which my mod captures it as a failed spawn. This therefore does not start the cooldown, which is why you see them spawn constantly. Then SpecialMobs respawns the mob, which I cannot detect directly, and therefore that mob doesnt get counted my my Spawn Summons capability.
> 
> I will try to figure this out but you may want to escalate this with the Special Mobs dev to see if they can do something on their side and link them this so they can see the explanation

Alrighty, thank you very much.

**Comment by Quarris** [comment]
I fixed the issue, as far as I am aware at least, the new version should be out on curseforge

**Comment by SSenZ0** [comment]
> I fixed the issue, as far as I am aware at least, the new version should be out on curseforge

You are a LEGEND!

**Comment by democat3457** [comment]
also also the dev is actually relatively active, you can check out his discord (and he actually just now released a new bugfix version of special mobs https://www.curseforge.com/minecraft/mc-mods/special-mobs/files/3319827)

**Comment by Quarris** [comment]
Wait, this is actually bad for me. That latest update breaks my fix for the issue. @SSenZ0 can you test v1.0.3 of special mobs to see how it handles?

**Comment by democat3457** [comment]
😳

**Comment by Quarris** [comment]
Okay v1.0.4 of special mobs seem to have refixed the issue
