### ISSUE TITLE
Is it possible to select for modded projectiles as a damage source?

### ISSUE THREAD

**Issue by roccscout** [Quarris/RebirthOfTheMobs#14]
Betteranimalsplus 1.12.2 has a Tarantula mob. This mob can spit "hairs" projectiles without warning that do too much damage, and I'd like to disable these hairs.

betteranimalsplus:tarantulahair is the "entity" that comes up, but I've tried:

 S:"Cancel Damage Sources" <
            minecraft:player;;betteranimalsplus:tarantulahair
            minecraft:player;;tarantulahair
         >
         
         And it doesn't work. Any ideas?

**Comment by Quarris** [comment]
Have you checked the logs? Is something fails to log it will let you know there. Whats the double ;; about?

**Comment by roccscout** [comment]
![image](https://user-images.githubusercontent.com/71896090/135148358-db4eec8f-016d-478b-8daf-0790c224593b.png)

Here's my config. Green arrows point to correcly working and formatted Cancel Damage Sources.

Log shows no errors with this format.

**Comment by Quarris** [comment]
Could you show me the log either way? It might just be the double ;; thats the issue. Optional values can be omitted entirely, not just left empty

**Comment by roccscout** [comment]
https://www.dropbox.com/s/wvnoadxpac64yxs/latest.log?dl=0

**Comment by roccscout** [comment]
https://www.dropbox.com/s/oio61nk04ih04ss/rotm.cfg?dl=1 

Here's my config file

**Comment by Quarris** [comment]
![image](https://user-images.githubusercontent.com/6171764/135154444-503a5594-8acd-41eb-bada-6cf56d97edf4.png)

**Comment by roccscout** [comment]
Yes, I'm aware. Those lines still function correctly in-game.

And they have nothing to do with the problem I'm asking about.

**Comment by Quarris** [comment]
Have you used the debug item that tells you the name of the damage source? Are you sure the damage source is called "tarantulahair"? It doesn't check for the entity that dealt the damage but the name of the damage source.

From what I can tell from looking at the mods source code it uses the "thrown" damage source

**Comment by roccscout** [comment]
I was going to say that the debug stick isn't working for this projectile. I'll try `thrown` and see if that work.

**Comment by roccscout** [comment]
`thrown` worked like a charm!

It's unfortunate that the debug stick doesn't show this damage type for some reason, but thank you for your effort! I appreciate it.
