### ISSUE TITLE
Ender Dragon not releasing spawns

### ISSUE THREAD

**Issue by lynaevm** [Quarris/RebirthOfTheMobs#3]
Posted a comment and am now upgrading it to an issue.

The Ender Dragon herself doesn't seem to release spawns as expected, though I have used the feature successfully with other mobs.  To make sure it wasn't some kind of interaction, I created a test instance with only minimal mods and used only minecraft creatures and still never saw a single summon.  There were no crashes or other aberrations with the fight.

Here is the script I used:
        S:"Summon Spawns" <
            minecraft:ender_dragon;minecraft:vex;80;6-8;10-20;false;true;80;true;false;true;minecraft:entity.enderdragon.growl;1
            minecraft:ender_dragon;minecraft:vex;60;6-8;10-20;false;true;80;true;false;true;minecraft:entity.enderdragon.growl;2
            minecraft:ender_dragon;minecraft:vex;40;6-8;10-20;false;true;80;true;false;true;minecraft:entity.enderdragon.growl;3
            minecraft:ender_dragon;minecraft:vex;20;2-4;10-20;false;true;80;true;false;true;minecraft:entity.enderdragon.growl;4
         >

**Comment by Quarris** [comment]
Did you attempt those settings for anything other than the dragon as well? I will test it out tomorrow and see if I can recreate it.

**Comment by Quarris** [comment]
I believe I have found the issue. Will try to sort this out soon. Apologies for taking so long

**Comment by lynaevm** [comment]
I'm glad you found a fix for this, thank you! When will you update the mod so I can play with it?

**Comment by Quarris** [comment]
*not* my apologies. Curseforge is yet again being a problem as it always is... I've just put it up for review (again, again) and I hope it'll go through good this time.
