### ISSUE TITLE
feature request: Dimension specificity

### ISSUE THREAD

**Issue by lynaevm** [Quarris/RebirthOfTheMobs#5]
It would be incredibly useful if you could optionally specify a dimension (or even a biome) for these behaviors so that you could use the same entities at different danger levels.

It might also be nice to be able to specify that the effects only be applied to a mob with a specific Name so that this mod could be used to beef up custom summoned mobs.

**Comment by Quarris** [comment]
This is a commission mod. If the original commissioner wants this feature I will add it then.
